from __future__ import annotations

import argparse
import json
import sys
from decimal import Decimal
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from data.common.db import db_cursor
from scripts.local_seed_common import (
    DATA_DIR,
    VariantContext,
    build_listing_description,
    compute_listing_mileage,
    compute_listing_price,
    ensure_placeholder_image,
    ensure_variant_specs,
    get_or_create_make,
    get_or_create_model,
    get_or_create_variant,
    insert_listing,
    listing_exists,
    listing_signature,
    pick_location,
    pick_owner_id,
)

REPORT_PATH = DATA_DIR / "local_seed_exotic_catalog_report.json"

EXOTIC_VARIANTS = [
    {
        "make_name": "Ferrari",
        "country_of_origin": "Italy",
        "model_name": "488 GTB",
        "segment": "coupe",
        "model_year": 2020,
        "trim_name": "Base",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "3.9L Twin-Turbo V8",
        "transmission": "7-Speed Dual-Clutch",
        "drivetrain": "Rear-Wheel Drive",
        "seats": 2,
        "doors": 2,
        "msrp_base": Decimal("15500000000"),
        "power_hp": 661,
        "torque_nm": 760,
        "displacement_cc": 3902,
        "length_mm": 4568,
        "width_mm": 1952,
        "height_mm": 1213,
        "wheelbase_mm": 2650,
        "curb_weight_kg": 1475,
    },
    {
        "make_name": "Ferrari",
        "country_of_origin": "Italy",
        "model_name": "F8 Tributo",
        "segment": "coupe",
        "model_year": 2021,
        "trim_name": "Base",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "3.9L Twin-Turbo V8",
        "transmission": "7-Speed Dual-Clutch",
        "drivetrain": "Rear-Wheel Drive",
        "seats": 2,
        "doors": 2,
        "msrp_base": Decimal("18900000000"),
        "power_hp": 710,
        "torque_nm": 770,
        "displacement_cc": 3902,
        "length_mm": 4611,
        "width_mm": 1979,
        "height_mm": 1206,
        "wheelbase_mm": 2650,
        "curb_weight_kg": 1435,
    },
    {
        "make_name": "Lamborghini",
        "country_of_origin": "Italy",
        "model_name": "Huracan",
        "segment": "coupe",
        "model_year": 2021,
        "trim_name": "EVO",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "5.2L V10",
        "transmission": "7-Speed Dual-Clutch",
        "drivetrain": "All-Wheel Drive",
        "seats": 2,
        "doors": 2,
        "msrp_base": Decimal("17500000000"),
        "power_hp": 631,
        "torque_nm": 600,
        "displacement_cc": 5204,
        "length_mm": 4520,
        "width_mm": 1933,
        "height_mm": 1165,
        "wheelbase_mm": 2620,
        "curb_weight_kg": 1422,
    },
    {
        "make_name": "Lamborghini",
        "country_of_origin": "Italy",
        "model_name": "Urus",
        "segment": "suv",
        "model_year": 2023,
        "trim_name": "S",
        "body_type": "suv",
        "fuel_type": "gasoline",
        "engine": "4.0L Twin-Turbo V8",
        "transmission": "8-Speed Automatic",
        "drivetrain": "All-Wheel Drive",
        "seats": 5,
        "doors": 4,
        "msrp_base": Decimal("12800000000"),
        "power_hp": 657,
        "torque_nm": 850,
        "displacement_cc": 3996,
        "length_mm": 5137,
        "width_mm": 2026,
        "height_mm": 1618,
        "wheelbase_mm": 3003,
        "curb_weight_kg": 2203,
    },
    {
        "make_name": "McLaren",
        "country_of_origin": "United Kingdom",
        "model_name": "720S",
        "segment": "coupe",
        "model_year": 2020,
        "trim_name": "Coupe",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "4.0L Twin-Turbo V8",
        "transmission": "7-Speed Dual-Clutch",
        "drivetrain": "Rear-Wheel Drive",
        "seats": 2,
        "doors": 2,
        "msrp_base": Decimal("18200000000"),
        "power_hp": 710,
        "torque_nm": 770,
        "displacement_cc": 3994,
        "length_mm": 4543,
        "width_mm": 1930,
        "height_mm": 1196,
        "wheelbase_mm": 2670,
        "curb_weight_kg": 1419,
    },
    {
        "make_name": "Porsche",
        "country_of_origin": "Germany",
        "model_name": "911",
        "segment": "coupe",
        "model_year": 2024,
        "trim_name": "Carrera S",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "3.0L Twin-Turbo Flat-6",
        "transmission": "8-Speed PDK",
        "drivetrain": "Rear-Wheel Drive",
        "seats": 4,
        "doors": 2,
        "msrp_base": Decimal("8200000000"),
        "power_hp": 443,
        "torque_nm": 530,
        "displacement_cc": 2981,
        "length_mm": 4519,
        "width_mm": 1852,
        "height_mm": 1300,
        "wheelbase_mm": 2450,
        "curb_weight_kg": 1545,
    },
    {
        "make_name": "Porsche",
        "country_of_origin": "Germany",
        "model_name": "911",
        "segment": "coupe",
        "model_year": 2024,
        "trim_name": "Turbo S",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "3.8L Twin-Turbo Flat-6",
        "transmission": "8-Speed PDK",
        "drivetrain": "All-Wheel Drive",
        "seats": 4,
        "doors": 2,
        "msrp_base": Decimal("12600000000"),
        "power_hp": 640,
        "torque_nm": 800,
        "displacement_cc": 3745,
        "length_mm": 4535,
        "width_mm": 1900,
        "height_mm": 1303,
        "wheelbase_mm": 2450,
        "curb_weight_kg": 1640,
    },
    {
        "make_name": "Audi",
        "country_of_origin": "Germany",
        "model_name": "R8",
        "segment": "coupe",
        "model_year": 2022,
        "trim_name": "V10 Performance quattro",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "5.2L V10",
        "transmission": "7-Speed Dual-Clutch",
        "drivetrain": "All-Wheel Drive",
        "seats": 2,
        "doors": 2,
        "msrp_base": Decimal("11700000000"),
        "power_hp": 602,
        "torque_nm": 560,
        "displacement_cc": 5204,
        "length_mm": 4429,
        "width_mm": 1940,
        "height_mm": 1240,
        "wheelbase_mm": 2650,
        "curb_weight_kg": 1695,
    },
    {
        "make_name": "Mercedes-Benz",
        "country_of_origin": "Germany",
        "model_name": "AMG GT",
        "segment": "coupe",
        "model_year": 2020,
        "trim_name": "R",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "4.0L Twin-Turbo V8",
        "transmission": "7-Speed Dual-Clutch",
        "drivetrain": "Rear-Wheel Drive",
        "seats": 2,
        "doors": 2,
        "msrp_base": Decimal("8900000000"),
        "power_hp": 577,
        "torque_nm": 700,
        "displacement_cc": 3982,
        "length_mm": 4551,
        "width_mm": 2007,
        "height_mm": 1284,
        "wheelbase_mm": 2630,
        "curb_weight_kg": 1630,
    },
    {
        "make_name": "BMW",
        "country_of_origin": "Germany",
        "model_name": "M4",
        "segment": "coupe",
        "model_year": 2024,
        "trim_name": "Competition xDrive",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "3.0L Twin-Turbo I6",
        "transmission": "8-Speed Automatic",
        "drivetrain": "All-Wheel Drive",
        "seats": 4,
        "doors": 2,
        "msrp_base": Decimal("4250000000"),
        "power_hp": 523,
        "torque_nm": 650,
        "displacement_cc": 2993,
        "length_mm": 4794,
        "width_mm": 1887,
        "height_mm": 1393,
        "wheelbase_mm": 2857,
        "curb_weight_kg": 1780,
    },
    {
        "make_name": "Nissan",
        "country_of_origin": "Japan",
        "model_name": "GT-R",
        "segment": "coupe",
        "model_year": 2021,
        "trim_name": "Premium",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "3.8L Twin-Turbo V6",
        "transmission": "6-Speed Dual-Clutch",
        "drivetrain": "All-Wheel Drive",
        "seats": 4,
        "doors": 2,
        "msrp_base": Decimal("5900000000"),
        "power_hp": 565,
        "torque_nm": 633,
        "displacement_cc": 3799,
        "length_mm": 4710,
        "width_mm": 1895,
        "height_mm": 1370,
        "wheelbase_mm": 2780,
        "curb_weight_kg": 1752,
    },
    {
        "make_name": "Chevrolet",
        "country_of_origin": "United States",
        "model_name": "Corvette",
        "segment": "coupe",
        "model_year": 2024,
        "trim_name": "Z06",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "5.5L V8",
        "transmission": "8-Speed Dual-Clutch",
        "drivetrain": "Rear-Wheel Drive",
        "seats": 2,
        "doors": 2,
        "msrp_base": Decimal("6400000000"),
        "power_hp": 670,
        "torque_nm": 624,
        "displacement_cc": 5495,
        "length_mm": 4688,
        "width_mm": 2025,
        "height_mm": 1234,
        "wheelbase_mm": 2722,
        "curb_weight_kg": 1623,
    },
    {
        "make_name": "Aston Martin",
        "country_of_origin": "United Kingdom",
        "model_name": "Vantage",
        "segment": "coupe",
        "model_year": 2022,
        "trim_name": "Coupe",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "4.0L Twin-Turbo V8",
        "transmission": "8-Speed Automatic",
        "drivetrain": "Rear-Wheel Drive",
        "seats": 2,
        "doors": 2,
        "msrp_base": Decimal("9400000000"),
        "power_hp": 503,
        "torque_nm": 685,
        "displacement_cc": 3982,
        "length_mm": 4465,
        "width_mm": 1942,
        "height_mm": 1273,
        "wheelbase_mm": 2704,
        "curb_weight_kg": 1590,
    },
    {
        "make_name": "Lexus",
        "country_of_origin": "Japan",
        "model_name": "LC",
        "segment": "coupe",
        "model_year": 2024,
        "trim_name": "500",
        "body_type": "coupe",
        "fuel_type": "gasoline",
        "engine": "5.0L V8",
        "transmission": "10-Speed Automatic",
        "drivetrain": "Rear-Wheel Drive",
        "seats": 4,
        "doors": 2,
        "msrp_base": Decimal("5700000000"),
        "power_hp": 471,
        "torque_nm": 540,
        "displacement_cc": 4969,
        "length_mm": 4770,
        "width_mm": 1920,
        "height_mm": 1345,
        "wheelbase_mm": 2870,
        "curb_weight_kg": 1935,
    },
]


def upsert_exotics(report_path: Path):
    report = {
        "input_variant_count": len(EXOTIC_VARIANTS),
        "makes_created": 0,
        "models_created": 0,
        "variants_created": 0,
        "variant_specs_created": 0,
        "placeholder_images_created": 0,
        "listings_created": 0,
        "items": [],
    }

    with db_cursor(dictionary=True) as (conn, cursor):
        for entry in EXOTIC_VARIANTS:
            make_id, make_created = get_or_create_make(
                cursor,
                name=entry["make_name"],
                country_of_origin=entry["country_of_origin"],
                is_placeholder=False,
            )
            model_id, model_created = get_or_create_model(
                cursor,
                make_id=make_id,
                name=entry["model_name"],
                segment=entry["segment"],
                is_placeholder=False,
            )
            variant_id, variant_created = get_or_create_variant(
                cursor,
                model_id=model_id,
                model_year=entry["model_year"],
                trim_name=entry["trim_name"],
                body_type=entry["body_type"],
                engine=entry["engine"],
                transmission=entry["transmission"],
                drivetrain=entry["drivetrain"],
                fuel_type=entry["fuel_type"],
                seats=entry["seats"],
                doors=entry["doors"],
                msrp_base=entry["msrp_base"],
                is_placeholder=False,
            )

            specs_created = ensure_variant_specs(
                cursor,
                variant_id,
                power_hp=entry.get("power_hp"),
                torque_nm=entry.get("torque_nm"),
                displacement_cc=entry.get("displacement_cc"),
                length_mm=entry.get("length_mm"),
                width_mm=entry.get("width_mm"),
                height_mm=entry.get("height_mm"),
                wheelbase_mm=entry.get("wheelbase_mm"),
                curb_weight_kg=entry.get("curb_weight_kg"),
            )
            placeholder_created = ensure_placeholder_image(
                cursor,
                variant_id=variant_id,
                body_type=entry["body_type"],
                fuel_type=entry["fuel_type"],
            )

            variant = VariantContext(
                variant_id=variant_id,
                make_name=entry["make_name"],
                model_name=entry["model_name"],
                model_year=entry["model_year"],
                trim_name=entry["trim_name"],
                body_type=entry["body_type"],
                fuel_type=entry["fuel_type"],
                transmission=entry["transmission"],
                drivetrain=entry["drivetrain"],
                engine=entry["engine"],
                seats=entry["seats"],
                doors=entry["doors"],
                msrp_base=entry["msrp_base"],
                power_hp=entry.get("power_hp"),
                displacement_cc=entry.get("displacement_cc"),
            )

            location_city, location_country = pick_location(variant, slot=0)
            owner_id = pick_owner_id(variant, slot=0)
            asking_price = compute_listing_price(variant, slot=0)
            mileage_km = compute_listing_mileage(variant, slot=0)
            description = build_listing_description(variant, slot=0)
            signature = listing_signature(
                owner_id,
                variant,
                location_city,
                location_country,
                asking_price,
                mileage_km,
            )
            listing_created = False
            if not listing_exists(cursor, signature):
                insert_listing(
                    cursor,
                    owner_id=owner_id,
                    variant=variant,
                    location_city=location_city,
                    location_country_code=location_country,
                    asking_price=asking_price,
                    mileage_km=mileage_km,
                    description=description,
                    status="active",
                )
                listing_created = True

            report["makes_created"] += int(make_created)
            report["models_created"] += int(model_created)
            report["variants_created"] += int(variant_created)
            report["variant_specs_created"] += int(specs_created)
            report["placeholder_images_created"] += int(placeholder_created)
            report["listings_created"] += int(listing_created)
            report["items"].append(
                {
                    "variant": variant.natural_label,
                    "make_created": make_created,
                    "model_created": model_created,
                    "variant_created": variant_created,
                    "listing_created": listing_created,
                }
            )

    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    return report


def main():
    parser = argparse.ArgumentParser(description="Seed exotic/performance catalog variants and showcase listings into the local DB only.")
    parser.add_argument("--report", type=Path, default=REPORT_PATH)
    args = parser.parse_args()

    report = upsert_exotics(args.report)
    print(json.dumps(report, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
